// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiKey": string;
      "baseUrl": string;
      "model": string;
      "maxTokens": number;
      "temperature": string;
      "systemPrompt": string;
      "zotaModelsCache": string;
      "panelMode": string;
      "keepWindowTop": boolean;
      "thinkingModeEnabled": boolean;
    };
  }
}
